// vue-project/src/App.vue
<template>
  <custom-uploader :files="files" accept="image/png,image/jpeg" multiple @change="handleChange">
    <div slot="tip">Some custom content</div>
  </custom-uploader>
</template>

<script setup lang="ts">
import { ref } from 'vue';

const files = ref<File[]>([])

function handleChange(event: CustomEvent<[File[]]>) {
  files.value = event.detail[0];
}
</script>

// react-project/src/App.tsx
import React, { useState, useRef, useEffect } from 'react';

function App() {
  const uploaderRef = useRef<React.JSX.IntrinsicElements['custom-uploader']>();
  const [files, setFiles] = useState<File[]>([]);

  useEffect(() => {
    function handleChange({ detail: [uploadedFiles] }: CustomEvent<[File[]]>) {
      if (uploadedFiles?.length) {
        if (uploaderRef.current) {
          uploaderRef.current.files = uploadedFiles;
        }
        setFiles(uploadedFiles);
      }
    }

    const uploader = uploaderRef.current;
    uploader?.addEventListener('change', handleChange as EventListener);

    return () => uploader?.removeEventListener('change', handleChange as EventListener);
  }, [files]);

  return (
    <custom-uploader multiple accept="image/png,image/jpeg" ref={uploaderRef}>
      <div slot="tip">Some custom tip content</div>
    </custom-uploader>
  );
}

export default App;
